name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl ufw xrdp

    - name: Download and Install Playit
      run: |
        curl -L "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64-signed.tar.gz" -o playit.tar.gz
        tar -xvzf playit.tar.gz
        sudo mv playit /usr/local/bin/
        rm playit.tar.gz

    - name: Enable RDP (Remote Desktop Protocol) and Configure xrdp
      run: |
        # Enable and start xrdp service
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389  # Open RDP port (3389)
        sudo ufw reload

    - name: Open Additional Port for Playit
      run: |
        # Open port 5000 for Playit
        sudo ufw allow 5000
        sudo ufw reload

    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }} 
      run: |
        # Start Playit with the authentication key
        playit --secret $PLAYIT_AUTH_KEY &
        # Ensure Playit runs continuously in the background
        nohup playit --secret $PLAYIT_AUTH_KEY &

    - name: Monitor Playit Process and Restart if Closed
      run: |
        while true; do
          if ! pgrep -x "playit" > /dev/null; then
            echo "Playit process not running. Restarting..."
            nohup playit --secret $PLAYIT_AUTH_KEY &
          fi
          sleep 10
        done

    - name: Run Playit as a Service (Secure Method)
      run: |
        # Create a systemd service for Playit to ensure it restarts if it crashes
        echo "[Unit]
        Description=Playit Service
        After=network.target

        [Service]
        ExecStart=/usr/local/bin/playit --secret $PLAYIT_AUTH_KEY
        Restart=always

        [Install]
        WantedBy=multi-user.target" | sudo tee /etc/systemd/system/playit.service
        sudo systemctl daemon-reload
        sudo systemctl enable playit
        sudo systemctl start playit

    - name: Block Unauthorized IPs
      run: |
        # Block unauthorized IPs using UFW
        sudo ufw deny from any to any port 3389
        sudo ufw deny from any to any port 5000
        sudo ufw reload

    - name: Keep GitHub Action Runner Alive
      run: |
        # Run a no-op task to keep the runner alive
        while true; do
          echo "Keeping GitHub Actions runner alive..."
          sleep 300
        done
