name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5  # Give some time for the download to complete

    # Enable RDP (Remote Desktop Protocol)
    - name: Enable TS (RDP)
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)

    # Open additional port for RDP or Playit
    - name: Open Additional Port for RDP or Playit
      run: |
        # Open an additional RDP port (example port 3390)
        netsh advfirewall firewall add rule name="Allow RDP 3390" dir=in action=allow protocol=TCP localport=3390
        # Open additional ports for Playit or other applications
        netsh advfirewall firewall add rule name="Allow Playit 5000" dir=in action=allow protocol=TCP localport=5000

    # Install Windows Defender if not already installed (ensure security)
    - name: Ensure Windows Defender is Running
      run: |
        Set-MpPreference -DisableRealtimeMonitoring $false  # Ensure Defender is running

    # Start Playit and Set Up RDP Tunnel
    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }} 
      run: |
        # Start Playit with the authentication key
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        # Ensure Playit runs continuously in the background
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow

    # Monitor Playit process and ensure it remains running
    - name: Monitor Playit and Restart if Closed
      run: |
        while ($true) {
            $playitProcess = Get-Process -Name "playit" -ErrorAction SilentlyContinue
            if ($null -eq $playitProcess) {
                Write-Host "Playit process is not running. Restarting..."
                Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow
                Start-Sleep -Seconds 5
            }
            Start-Sleep -Seconds 10  # Check every 10 seconds

    # Run Playit as a Service (Secure Method)
    - name: Run Playit as a Service (Secure Method)
      run: |
        # Set Playit as a service to auto-restart if it crashes
        New-Service -Name "PlayitService" -Binary "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -StartupType Automatic
        Start-Service "PlayitService"

    # Additional Security Measures: Block unauthorized IPs
    - name: Block Unauthorized IPs for RDP and Playit
      run: |
        # Add rule to block unauthorized IP addresses (adjust as needed)
        netsh advfirewall firewall add rule name="Block Unauthorized IPs" dir=in action=block protocol=TCP remoteip=0.0.0.0/0 localport=3389,3390
        netsh advfirewall firewall add rule name="Block Unauthorized Playit IPs" dir=in action=block protocol=TCP remoteip=0.0.0.0/0 localport=5000

    # Keep GitHub Action Runner Alive
    - name: Keep GitHub Action Runner Alive in Multiple Tabs
      run: |
        # Run a no-op task to keep the runner alive
        Start-Job -ScriptBlock {
            while ($true) {
                Write-Host "Keeping GitHub Actions runner alive..."
                $null = Get-Process 
                Start-Sleep -Seconds 300  # Sleep for 5 minutes
            }
        }

        # Run a background job for Playit process monitoring
        Start-Job -ScriptBlock {
            while ($true) {
                Write-Host "Monitoring Playit process..."
                $playitProcess = Get-Process -Name "playit" -ErrorAction SilentlyContinue
                if ($null -eq $playitProcess) {
                    Write-Host "Playit process is not running. Restarting..."
                    Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow
                }
                Start-Sleep -Seconds 15  # Check every 15 seconds
            }
        }

        # Wait for background jobs to ensure continuous operation
        while ($true) {
            Start-Sleep -Seconds 60  # Keep the main job running indefinitely
        }
